Feature4
mudasiri/Vet-Clinic pull request #4
Opened 2023-04-01 22:59 UTC by mudasiri

In this Pull request I have done the features base on requirements of project below:

### Project requirements
- Create a table named `vets` with the following columns:
  - `id`: integer (set it as autoincremented PRIMARY KEY)
  - `name`: string
  - `age`: integer
  - `date_of_graduation`: date
- There is a **many-to-many** relationship between the tables `species` and `vets`: a vet can specialize in multiple species, and a species can have multiple vets specialized in it. Create a "join table" called `specializations` to handle this relationship.
- There is a **many-to-many** relationship between the tables `animals` and `vets`: an animal can visit multiple vets and one vet can be visited by multiple animals. Create a "join table" called `visits` to handle this relationship, it should also keep track of the date of the visit.
- Insert the following data for vets:
  - Vet William Tatcher is 45 years old and graduated Apr 23rd, 2000.
  - Vet Maisy Smith is 26 years old and graduated Jan 17th, 2019.
  - Vet Stephanie Mendez is 64 years old and graduated May 4th, 1981.
  - Vet Jack Harkness is 38 years old and graduated Jun 8th, 2008.
- Insert the following data for specialties:
  - Vet William Tatcher is specialized in Pokemon.
  - Vet Stephanie Mendez is specialized in Digimon and Pokemon.
  - Vet Jack Harkness is specialized in Digimon.
- Insert the following data for visits:
  - Agumon visited William Tatcher on May 24th, 2020.
  - Agumon visited Stephanie Mendez on Jul 22th, 2020.
  - Gabumon visited Jack Harkness on Feb 2nd, 2021.
  - Pikachu visited Maisy Smith on Jan 5th, 2020.
  - Pikachu visited Maisy Smith on Mar 8th, 2020.
  - Pikachu visited Maisy Smith on May 14th, 2020.
  - Devimon visited Stephanie Mendez on May 4th, 2021.
  - Charmander visited Jack Harkness on Feb 24th, 2021.
  - Plantmon visited Maisy Smith on Dec 21st, 2019.
  - Plantmon visited William Tatcher on Aug 10th, 2020.
  - Plantmon visited Maisy Smith on Apr 7th, 2021.
  - Squirtle visited Stephanie Mendez on Sep 29th, 2019.
  - Angemon visited Jack Harkness on Oct 3rd, 2020.
  - Angemon visited Jack Harkness on Nov 4th, 2020.
  - Boarmon visited Maisy Smith on Jan 24th, 2019.
  - Boarmon visited Maisy Smith on May 15th, 2019.
  - Boarmon visited Maisy Smith on Feb 27th, 2020.
  - Boarmon visited Maisy Smith on Aug 3rd, 2020.
  - Blossom visited Stephanie Mendez on May 24th, 2020.
  - Blossom visited William Tatcher on Jan 11th, 2021.
- Write queries to answer the following:
  - Who was the last animal seen by William Tatcher?
  - How many different animals did Stephanie Mendez see?
  - [List all vets and their specialties, including vets with no specialties.](https://github.com/mudasiri/Vet-Clinic/blob/Feature4/images/day%204/vets%20no%20specialities.png)
  - List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
  - [What animal has the most visits to vets?](https://github.com/mudasiri/Vet-Clinic/blob/Feature4/images/day%204/animal_mostvisits.png)
  - [Who was Maisy Smith's first visit?](https://github.com/mudasiri/Vet-Clinic/blob/Feature4/images/day%204/maisy%20first%20visit.png)
  - Details for most recent visit: animal information, vet information, and date of visit.
  - How many visits were with a vet that did not specialize in that animal's species?
  - What specialty should Maisy Smith consider getting? Look for the species she gets the most.
- **Take a screenshot of the results of your queries.**
- Remember to add the screenshot with the results of your queries to your Pull Request description.

2023-04-01 23:21 UTC, Davidosky007 requested changes
Hi @mudasiri 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Well written PR 👍 
* Good looking readme file 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 23:21 UTC, Davidosky007 commented on schema.sql
> +create table specializations (species_id INT, vets_id INT);
* Kindly add all these data below 👇 as it is a[ requirement ](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_join_table.md#:~:text=Insert%20the%20following,Jan%2011th%2C%202021.)

> Insert the following data for vets:
> Vet William Tatcher is 45 years old and graduated Apr 23rd, 2000.
> Vet Maisy Smith is 26 years old and graduated Jan 17th, 2019.
> Vet Stephanie Mendez is 64 years old and graduated May 4th, 1981.
> Vet Jack Harkness is 38 years old and graduated Jun 8th, 2008.
> Insert the following data for specialties:
> Vet William Tatcher is specialized in Pokemon.
> Vet Stephanie Mendez is specialized in Digimon and Pokemon.
> Vet Jack Harkness is specialized in Digimon.
> Insert the following data for visits:
> Agumon visited William Tatcher on May 24th, 2020.
> Agumon visited Stephanie Mendez on Jul 22th, 2020.
> Gabumon visited Jack Harkness on Feb 2nd, 2021.
> Pikachu visited Maisy Smith on Jan 5th, 2020.
> Pikachu visited Maisy Smith on Mar 8th, 2020.
> Pikachu visited Maisy Smith on May 14th, 2020.
> Devimon visited Stephanie Mendez on May 4th, 2021.
> Charmander visited Jack Harkness on Feb 24th, 2021.
> Plantmon visited Maisy Smith on Dec 21st, 2019.
> Plantmon visited William Tatcher on Aug 10th, 2020.
> Plantmon visited Maisy Smith on Apr 7th, 2021.
> Squirtle visited Stephanie Mendez on Sep 29th, 2019.
> Angemon visited Jack Harkness on Oct 3rd, 2020.
> Angemon visited Jack Harkness on Nov 4th, 2020.
> Boarmon visited Maisy Smith on Jan 24th, 2019.
> Boarmon visited Maisy Smith on May 15th, 2019.
> Boarmon visited Maisy Smith on Feb 27th, 2020.
> Boarmon visited Maisy Smith on Aug 3rd, 2020.
> Blossom visited Stephanie Mendez on May 24th, 2020.
> Blossom visited William Tatcher on Jan 11th, 2021.

2023-04-01 23:21 UTC, Davidosky007 commented on schema.sql
> +SELECT COUNT(animals.name)
* Kindly move all your queries into the `qeuries.sql` file as its best practice

2023-04-04 04:08 UTC, BenMukebo requested changes
Hi  @mudasiri, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- Gitflow is followed. :heavy_check_mark:
- PR has a good title and summary. ✔️


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly, let's add correct information to the  `Show your support` and `Acknowledgments` section of the README file, This should have correct information. ✍🏻 

![image](https://user-images.githubusercontent.com/79058364/229684793-466b1bca-9f9e-4685-b09c-1da8cc508d0d.png)


- [ ]  I'd recommend that you delete the Note: 👇🏻 in your License section as these are instructions on how to complete the License section.


![image](https://user-images.githubusercontent.com/79058364/220769702-9dbcadda-aa00-4d1c-990f-cf6ad4f5c6c9.png)


You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 04:08 UTC, BenMukebo commented on data.sql
> +INSERT INTO visits (animals_id, vets_id, date_of_visit) VALUES (3, 2, '2020-05-08');
- [ ]Please pay more attention when inserting our data for visits, here are the project requirements 👇🏻 if you pay more attention to the fifth insert you can see it has 'mar' as the month which is the short form of March, not May. Please fix that 👍🏻
 
![image](https://user-images.githubusercontent.com/79058364/229682487-0dccb9b8-37f5-4d31-bee9-c09d1d5e0616.png)

- Your code might look like this 👇🏻 

`INSERT INTO visits (animal_id, vet_id, vist_date) VALUES ((SELECT id FROM animal WHERE name = 'Pikachu'), (SELECT id FROM vets WHERE name = 'Maisy Smith'), '2020-03-08');`

2023-04-04 04:08 UTC, BenMukebo commented on queries.sql
> +SELECT COUNT(animals.name)
- [ ] According to the project requirements. Add a screenshot of the query results to the pull request description. This also helps to ensure that you run the queries with success. Kindly make this 💯 👍🏻

2023-04-07 00:34 UTC, franclobo reviewed
Hi @mudasiri, 

![terminator](https://user-images.githubusercontent.com/58642949/230517275-db723d0a-fbd1-41e7-b7cb-635f9091c12f.gif)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have professional documentation. All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo. Please edit your README with the correct information of the current project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-07 00:49 UTC, franclobo reviewed
Hi @mudasiri, 

![roja](https://user-images.githubusercontent.com/58642949/230518611-50b016a5-54b6-4069-836a-3d954c786752.jpg)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a professional README file. Please 🙏🏽 remove the FAQ section if you don't have questions and answers about the current project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-07 01:05 UTC, Reem-lab approved these changes
# Hi @mudasiri,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥💯💯
<img src="https://media2.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>

## Highlights 🔥🔥🔥🔥
- Followed Gitflow ✅
- Great working on the functionality 🔥🔥




## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 01:09 UTC, merged

2023-05-03 08:34 UTC, mikethreels reviewed
Hi Muda, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- great job creating the queries.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._